services:
  nexusrag-web:
    build:
      context: .
      target: builder
    command: streamlit run app.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  nexusrag-api:
    build:
      context: .
      target: builder
    command: python -m nexusrag.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
